[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Thomas Hiscock <thomas.hiscock@wanadoo.fr>"]
edition = "2018"

[dependencies]
scan_fmt = ">=0.1.3"
regex = ">=1.1.0"
itertools = ">=0.8.0"
pathfinding = ">=1.1.10"
